version: v1.0

name: "Config Deploy"

agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004

global_job_config:
  secrets:
    - name: secrets

blocks:

  - name: "Publish Config"

    task:

      prologue:
        commands:
            - tar xzf /home/semaphore/secrets/secrets.tar.gz -C /home/semaphore/secrets
            - gcloud auth activate-service-account --key-file=/home/semaphore/secrets/terraform-storage.json
            - export SDK_CONFIG_BUCKET=gs://sloclap_network_next_sdk_config

      jobs:

        - name: "Config"
          commands:
            - artifact pull workflow google.txt
            - artifact pull workflow amazon.txt
            - artifact pull workflow akamai.txt
            - artifact pull workflow unity.txt
            - gsutil cp google.txt $SDK_CONFIG_BUCKET
            - gsutil cp amazon.txt $SDK_CONFIG_BUCKET
            - gsutil cp akamai.txt $SDK_CONFIG_BUCKET
            - gsutil cp unity.txt $SDK_CONFIG_BUCKET
